### ISSUE TITLE
custom .collapse definition in aldryn-bootstrap3 base.css messes up bootstrap menu

### ISSUE THREAD

**Issue by macolo** [aldryn/aldryn-bootstrap3#104]
It seems that this 

https://github.com/aldryn/aldryn-bootstrap3/blob/master/aldryn_bootstrap3/static/aldryn_bootstrap3/css/base.css#L10

messes up the bootstrap3 nav widget in mobile modus: http://getbootstrap.com/components/#navbar

It contains a class '.collapse' that is responsible for setting the height to 0 by default.

However, when the base.css is included on the page, the navbar below 768px window width is then open instead of closed by default.

the aldryn-bootstrap3 base.css is only included when there is an aldryn-bootstrap3 image element included on the page, and it appears also only in edit mode.

**Comment by aidan2129** [comment]
+1

**Comment by aidan2129** [comment]
Any solution for this yet base.css overrides bootstrap's collapse method when the django cms admin is active.

**Comment by vxsx** [comment]
solution would be to extract things that are necessary for the image plugin into a stylesheet that doesn't contain whole bootstrap installation

**Comment by aidan2129** [comment]
yeah i just cloned the app and changed it myself

**Comment by FinalAngel** [comment]
Collapse is not available anymore in the upcoming 1.2.0 release :)
