### ISSUE TITLE
Link/Button and Icon plugins "invisible" in text editor

### ISSUE THREAD

**Issue by lmanzurv** [aldryn/aldryn-bootstrap3#112]
When you add a Link/Button or an Icon plugin inside the text editor, these are added to the editor (you can see the <cmsplugin> tag in HTML view) but they are invisible, rendering them useless because they can't be edited afterwards.

In the case of the Icon, it happens every time, but in the case of the Link/Button, it only happens if the button has no label (if it has children or just icons it doesn't show).

The following images show a text editor with a link and an icon, which can be seen in the HTML view, but not in the preview, thus they can't be edited.

![screen shot 2016-10-26 at 2 45 58 pm](https://cloud.githubusercontent.com/assets/3003634/19726396/0ff03458-9b8b-11e6-9498-1d4779766516.png)
![screen shot 2016-10-26 at 2 46 05 pm](https://cloud.githubusercontent.com/assets/3003634/19726398/11cfd526-9b8b-11e6-9320-af81d0ab4b57.png)

**Comment by georgema1982** [comment]
Agree. The invisible icons are very annoying when editing the text.

**Comment by vxsx** [comment]
The issue here is missing configuration. CKEditor by default doesn't provide any styles, and has specific default options. For example - it removes empty `span` tags. You may also notice that links are not of the same color as in your website for example. 

To fix this, you should configure the CKEditor plugin to use your stylesheet and not remove the empty spans, like this: 

Settings: https://github.com/divio/django-cms-demo/blob/master/src/settings.py#L318-L324
js: https://github.com/divio/django-cms-explorer/blob/master/static/js/addons/ckeditor.wysiwyg.js#L73 (you can use whole file, relevant line is highlighted)

**Comment by georgema1982** [comment]
I'm running django-cms-demo but I still can't see icon in the editor

**Comment by vxsx** [comment]
That's weird. Do you see the ckeditor.wysiwyg.js being loaded in browser devtools when the plugin edit modal is open? Are there any errors in the console?

**Comment by georgema1982** [comment]
Now I see the icon in the editor. Not sure what happened the first time.

**Comment by vxsx** [comment]
Great to hear! @lmanzurv does [this](https://github.com/aldryn/aldryn-bootstrap3/issues/112#issuecomment-265686941) solve your issue?

**Comment by lmanzurv** [comment]
No. The JS is being loaded (I added it because I didn't have it before) but it still is invisible. Not really sure what else I'm supposed to do

**Comment by vxsx** [comment]
Are the styles also there @lmanzurv ? Now that you have the js in place the spans shouldn't disappear from the "Source" panel in ckeditor

**Comment by lmanzurv** [comment]
The spans are still disappearing and there is no styles (we are setting styles through an admin editor). The spans have never disappeared from the Source panel, they disappear from the rich editor

**Comment by vxsx** [comment]
But if the spans are there in the source it means that they aren't styled if they don't show up in the rich editor.

I.e. this is what i see if there are no styles applied through `stylesSet`
![screen shot 2016-12-13 at 11 05 23](https://cloud.githubusercontent.com/assets/366813/21136010/2c00a6f0-c124-11e6-8010-3e0801c14b03.png)


and this is what i see if there are styles:
![screen shot 2016-12-13 at 11 05 08](https://cloud.githubusercontent.com/assets/366813/21136016/34caaf1a-c124-11e6-88f0-2bdcc6611c5c.png)

Could you elaborate on "we are setting styles through an admin editor"?

**Comment by lmanzurv** [comment]
We developed a custom plugin for CMS that allows us to change the CSS through the admin, so the project has no CSS as static. The CSS from the custom editor is inserted in the HTML using template tags

**Comment by vxsx** [comment]
I see. The CKEditor itself only supports contentCss injected as a filepath afaik http://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-contentsCss so sadly can't really help you with that.

**Comment by lmanzurv** [comment]
Is there any base CSS (generic styles) that could be used to force it to render?

Laura C. Manzur V.
Systems and Computing Engineer, M.Sc.
Universidad de los Andes
Mobile: +27 063 266 6884
Cape Town, South Africa

**Comment by FinalAngel** [comment]
@lmanzurv you need to apply the css to the CKEditor as @vxsx described, otherwise CKEditor won't render your content (as it uses an iframe to load the content)

**Comment by lmanzurv** [comment]
I applied the base CSS from the explorer theme and it still presents the issue. When I edit an existing link, it disappears if it only has an icon and no text.

**Comment by georgema1982** [comment]
@lmanzurv Try setting a bootstrap css cdn link (eg. https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css) to contentCss if icons are that concern you.

**Comment by lmanzurv** [comment]
@georgema1982 already tried with bootstrap. Still turning invisible. They are important because we sometimes want to display links that are only icons. This is the way we have found is simplest to achieve this. The problem is you edit them and they disappear. It requires to save the text plugin and reopen it to view the plugin again...

**Comment by leety** [comment]
I have encountered the same issue.  So I followed vxsx's suggestion and applied the changes to settings.py.  So right now, the empty <span> tag would remain, and the static base.css would load as well.  The styles are applied according; however, this is what I see for the icons.
![free](https://cloud.githubusercontent.com/assets/10430147/22352737/5c9862e6-e3eb-11e6-948f-e7b20efed941.png)
After fixing the path to the webfonts in the base.css file, everything is working as it should.

**Comment by mshava** [comment]
Hello guys, I'm a newbie to djangocms and I've already find some useful answers on this platform. Thanks to all of you guys but a question though, I'm suppose to build a map using alias plugin but I'm struggling here... Can anyone help please.

Thank you.

**Comment by shrimpchip28** [comment]
I just ran into the same issue.  Followed @vxsx suggestion. Had to add font-awesome.min.css to the list of css files in the contentsCss list in addition to bootstrap css.  I also added additional css to adjust the positioning of typed text in the editor - see below the CKEDITOR_SETTINGS that need to be added to settings.py.  Make sure you download the ckeditor.wysiwyg.js file that @vxsx references.  You can add the CKEDITOR_SETTINGS as described in his post at the end of the settings.py file. 

![image](https://user-images.githubusercontent.com/2615523/34903391-7fb939b2-f7e5-11e7-8a79-d93c77f9301e.png)
