### ISSUE TITLE
Image resize on select (Carousel)

### ISSUE THREAD

**Issue by sonic182** [aldryn/aldryn-bootstrap3#115]
Hi

Would be great if there was an option to make a thumbnail when selecting image for carousel. To optimize pageloads and avoid user to do it by photoshop or something like that.

Let me know if this issue could be a good feature to start doing it or if not to don't do it :)

**Comment by FinalAngel** [comment]
@sonic182 I do not really understand what you'd like to achieve with a "thumbnail". You can select the "aspect ratio" dropdown to get the images automatically cropped on display.

The images are automatically croppped to the placeholder width, so it does not matter how large the image is when you upload it.

**Comment by FinalAngel** [comment]
@sonic182 would you be able to provide additional information?

**Comment by sonic182** [comment]
Mmm no, the "aspect ratio" is all that I needed, maybe if it could exist
something to slow down quality of image, to optimize page loads would be
great, something to indicate the quality of the picture from 0 to 100%

**Comment by FinalAngel** [comment]
@sonic182 I'd suggest that you open a ticket on https://github.com/divio/django-filer for this, as that feature needs to be implemented in filer itself. Closing this then for now :)
