### ISSUE TITLE
Space doesn't work.

### ISSUE THREAD

**Issue by GianlucaScarciolla** [aldryn/aldryn-bootstrap3#117]
Hey.
After I added the _Space_ to the Placeholder and saved, there was no **Space** between the two _Row's_.

**Comment by FinalAngel** [comment]
@GianlucaScarciolla space is not an "official" plugin of bootstrap3 (it will be in bootstrap4) so you have to add the classes to your own stylesheet. I'll make sure a not regarding this will be added in the README.

**Comment by GianlucaScarciolla** [comment]
thank you for the response! I will check it out later.

**Comment by FinalAngel** [comment]
@GianlucaScarciolla see https://github.com/aldryn/aldryn-bootstrap3/pull/122 for infos on how you might configure the spacer plugin
