### ISSUE TITLE
Button Plugin shows icons in preview initially

### ISSUE THREAD

**Issue by stefanfoulis** [aldryn/aldryn-bootstrap3#123]
Even if no icons are selected in the options, the preview at the top of the page always loads with the "default" icon displayed. Only activating and deactivating the icon option on the form will make it go away from the preview.

**Comment by FinalAngel** [comment]
@stefanfoulis I checked and the icon is not being displayed when selecting a button:

![image](https://cloud.githubusercontent.com/assets/270307/22156964/e7e8f730-df35-11e6-898e-fb608911f523.png)
