### ISSUE TITLE
Page headers implementation

### ISSUE THREAD

**Issue by dylansteele8** [aldryn/aldryn-bootstrap3#149]
When will the page header plugin be implemented? Will it allow an image to be placed in the background like with the carousel?

**Comment by FinalAngel** [comment]
@dylansteele8 there are current no plans on adding additional components including the page header. You can easily add a page header class using djangocms-style (https://github.com/divio/djangocms-style)

In regards to the background image, even if we implement the page header, it would just generate a ``<div class="page-header"> ... </div>`` element with the option of adding attributes to it. If you have specific use cases I'd recommend creating a specific plugin for your needs or checkout https://github.com/aldryn/aldryn-background-image. Also djangocms-picture has the capabilities of adding background images and alter the generated HTML via templates: https://github.com/divio/djangocms-picture#configuration

Is that sufficient enough for you?

**Comment by dylansteele8** [comment]
Yep, thanks so much for the help! Looks like djangocms-style can do what I need.
