### ISSUE TITLE
Support for django 1.11

### ISSUE THREAD

**Issue by django-user** [aldryn/aldryn-bootstrap3#157]
I'm trying out aldryn-bootstrap3 with Django 1.11.3 and I get the following error:

  File "/opt/myvirtualenv/project_virtual_env/lib/python3.5/site-packages/aldryn_bootstrap3/widgets.py", line 10, in <module>
    class ContextRenderer(django.forms.widgets.RadioFieldRenderer):
AttributeError: module 'django.forms.widgets' has no attribute 'RadioFieldRenderer'

**Comment by aaratn** [comment]
+1

**Comment by wismill** [comment]
+1 This plugin is using undocumented classes of Django.
Relevant changelog: https://docs.djangoproject.com/en/1.11/releases/1.11/#changes-due-to-the-introduction-of-template-based-widget-rendering
Django-CMS 3.4.5 is compatible with Django 1.11.

**Comment by wismill** [comment]
Migth help: https://stackoverflow.com/questions/45726609/render-radio-buttons-without-ul-in-django-1-11

**Comment by brmejia** [comment]
+1

**Comment by horejsek** [comment]
Does anyone work on it?

**Comment by Natureshadow** [comment]
+1

I cannot upgrade because of this…

**Comment by JurajKavka** [comment]
+1

`aldryn-bootstrap3==1.2.2` does not work witn Django 1.11

**Comment by horejsek** [comment]
I don't like this solution but I made it work with some copy&paste of removed classes from Django 1.10:

https://gitlab.labs.nic.cz/websites/django-cms-qe/blob/master/cms_qe/django_111_compatibility.py

**Comment by russmo** [comment]
See latest at #161 for Django 1.11 and 2.0 compatibility pull request.

**Comment by czpython** [comment]
Fixed by https://github.com/aldryn/aldryn-bootstrap3/pull/161
