### ISSUE TITLE
Creating Map Alias

### ISSUE THREAD

**Issue by mshava** [aldryn/aldryn-bootstrap3#162]
Hello guys, I'm a newbie to djangocms and I've already find some useful answers on this platform. Thanks to all of you guys but a question though, I'm suppose to build a map using alias plugin but I'm struggling here... Can anyone help please.

Thank you.

**Comment by vxsx** [comment]
Hi @mshava 
aldryn-bootstrap3 doesn't have a map plugin, so i'm not really sure what are you referring to.

You might have better luck asking the question on https://stackoverflow.com/
