### ISSUE TITLE
AttributeError: module 'django.forms.widgets' has no attribute 'RadioFieldRenderer'

### ISSUE THREAD

**Issue by fmurer** [aldryn/aldryn-bootstrap3#169]
After `pip install aldryn-bootstrap3` and adding `aldryn_bootstrap3` to `INSTALLED_APPS`, I get the following error when migrating:

AttributeError: module 'django.forms.widgets' has no attribute 'RadioFieldRenderer'

**Comment by nicodelara** [comment]
Hi. see this link https://github.com/aldryn/aldryn-bootstrap3/issues/157

**Comment by czpython** [comment]
Fixed by https://github.com/aldryn/aldryn-bootstrap3/pull/161
