### ISSUE TITLE
Icons are not properly shown in the text plugin

### ISSUE THREAD

**Issue by georgema1982** [aldryn/aldryn-bootstrap3#18]
After I select one icon in the text plugin, it doesn't show properly in the text editor. Please see the screenshot below.

![bs3icons](https://cloud.githubusercontent.com/assets/727970/7900677/1b679e14-0723-11e5-8225-4ae8a9e36a43.jpg)
Am I missing something here?

**Comment by FinalAngel** [comment]
images are now included in develop, will release soon
