### ISSUE TITLE
Python 3 environment, migration issue

### ISSUE THREAD

**Issue by asselapathirana** [aldryn/aldryn-bootstrap3#25]
With python 3, the following error occurs: 
aldryn_bootstrap3/forms.py", line 138
    print style
(fixing like print(style) will work. 

Is aldryn-bootstrap3 supposed to be used only with Python 2.x?

**Comment by zemyatin** [comment]
Please fix this and update the pip PyPi. I made the change locally all works as it should.

**Comment by FinalAngel** [comment]
has been removed, releasing as develop gets merged
