### ISSUE TITLE
Link/Button plugin additional attributes

### ISSUE THREAD

**Issue by ruslanmalogulko** [aldryn/aldryn-bootstrap3#30]
We need to add additional fields inside this plugin for having possibility to add custom attributes for button. For example for analytics it should be possible to add some custom data attributes, etc.

**Comment by vxsx** [comment]
:+1: it would be great to have data-attributes (not only on buttons), would provide a lot of flexibility for advanced users

**Comment by stefanfoulis** [comment]
:+1: for a generic way to add data attributes (a custom field that can be used on all plugins, not just button).

**Comment by matzegebbe** [comment]
I´m new to DjangoCMS. How can I add the custom field to a plugin? In need the "data-toggle" attribute

**Comment by vxsx** [comment]
Should be possible now since https://github.com/aldryn/aldryn-bootstrap3/pull/92 is merged
