### ISSUE TITLE
migrations broken

### ISSUE THREAD

**Issue by kakulukia** [aldryn/aldryn-bootstrap3#33]
i just tried to install this plugin'

the dependencies were installed:
Successfully installed aldryn-bootstrap3-0.5.1 django-durationfield-0.5.2 django-filer-0.9.12

BUT the migrations are not running:
Migration cmsplugin_filer_image.0001_initial dependencies reference nonexistent parent node (u'filer', u'0001_initial')

**Comment by stpdev** [comment]
I'm trying to manage.py migrate aldryn_bootstrap3, but recieve an error message:
'''
    (mblg)stp@Machinko ~/web/myblog $ python manage.py migrate aldryn_bootstrap3
    CommandError: System check identified some issues:
    
    ERRORS:
    aldryn_bootstrap3.Boostrap3ButtonPlugin.link_file: (fields.E300) Field defines a relation with model 'File', which is either not installed, or is abstract.
    aldryn_bootstrap3.Boostrap3ImagePlugin.file: (fields.E300) Field defines a relation with model 'Image', which is either not installed, or is abstract.
    aldryn_bootstrap3.Bootstrap3CarouselSlideFolderPlugin.folder: (fields.E300) Field defines a relation with model 'Folder', which is either not installed, or is abstract.
    aldryn_bootstrap3.Bootstrap3CarouselSlidePlugin.image: (fields.E300) Field defines a relation with model 'Image', which is either not installed, or is abstract.
    aldryn_bootstrap3.Bootstrap3CarouselSlidePlugin.link_file: (fields.E300) Field defines a relation with model 'File', which is either not installed, or is abstract.
    aldryn_bootstrap3.Bootstrap3FilePlugin.file: (fields.E300) Field defines a relation with model 'File', which is either not installed, or is abstract.
'''

**Comment by LepusSorbas** [comment]
Same Problem like kakulukia. You already found the Solution?

**Comment by kakulukia** [comment]
I just hate DjangoCMS by now .. its too messed up .. i switched to Wagtail which is doing the stuff i need in a much cleaner way and has no incomplete dependencies.

**Comment by cyberstar** [comment]
Hi @kakulukia  and @LepusSorbas (maybe more...).
Can you please ensure that filer is listed among ``INSTALLED_APPS`` in your ``settings.py`` ?
Also if that is not the case I assume that you are using ``Django >=1.7`` which means that on ``django-filer<1.0.0`` you also need to add it in ``MIGRATION_MODULES`` (not needed for >1.0.0 versions)

    MIGRATION_MODULES = {
        . . .
        'filer': 'filer.migrations_django',
    }

for ``Django<1.7`` you might need to configure ``SOUTH_MIGRATION_MODULES`` with 'filer': 'filer.south_migrations' depending on your ``south`` version.
