### ISSUE TITLE
Can't migrate aldryn-bootstrap3

### ISSUE THREAD

**Issue by LepusSorbas** [aldryn/aldryn-bootstrap3#38]
I successfully installed django-filer 
<code>$ pip install django-filer</code>
<code>$ Successfully installed Unidecode-0.4.18 django-filer-1.0.0 django-mptt-0.7.4 django-polymorphic-0.7.2 easy-thumbnails-2.2</code>

then I added them to INSTALLED_APPS
'filer',
'mptt',
'polymorphic',
'easy_thumbnails',
Migrated them everything fine until here, then I installed aldryn-bootstrap3 
<code>$ pip install aldryn-bootstrap3</code>
Aslo added 'aldryn_bootstrap3' to INSTALLED_APPS but then when I run migrations I get following error: 
<code>KeyError: u"Migration aldryn_bootstrap3.0001_initial dependencies reference nonexistent parent node (u'filer', u'0002_auto_20150606_2003')"</code>
Any Ideas how I can solve this?
I'm using django 1.7 and python2.7

**Comment by FinalAngel** [comment]
@LepusSorbas which filer and bootstrap3 version get installed?

**Comment by cyberstar** [comment]
@LepusSorbas this might be related to https://github.com/stefanfoulis/django-filer/issues/602 
please use filer of at least 1.0.2 version

**Comment by LepusSorbas** [comment]
Thanks for respond guys! Now I upgraded filer to 1.0.2 aldryn-bootstrap to 1.0.1 and django to 1.8 and now I get the following error:
<code>django.db.migrations.graph.NodeNotFoundError: Migration aldryn_bootstrap3.0001_initial dependencies reference nonexistent parent node (u'filer', u'0002_auto_20150606_2003')</code>

**Comment by cyberstar** [comment]
@LepusSorbas can you please provide a little bit more info on your setup?
please paste here your database settings (without logins and passwords), the exact command that you use to run this migration, ``INSTALLED_APPS`` and if you have ``MIGRATION_MODULES`` in your settings - paste them here also.


since all files are in place in the repo - I assume that this is only a misconfiguration issue.
https://github.com/stefanfoulis/django-filer/tree/develop/filer/migrations

**Comment by LepusSorbas** [comment]
Ok 
My INSTALLED_APPS: 
<pre> 
INSTALLED_APPS = (
    'djangocms_admin_style',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.admin',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.staticfiles',
    'django.contrib.messages',
    'filer',
    'mptt',
    'polymorphic',
    'easy_thumbnails',
    'aldryn_bootstrap3',
    'cms',
    'menus',
    'sekizai',
    'treebeard',
    'djangocms_text_ckeditor',
    'djangocms_style',
    'djangocms_column',
    'djangocms_file',
    'djangocms_flash',
    'djangocms_googlemap',
    'djangocms_inherit',
    'djangocms_link',
    'djangocms_picture',
    'djangocms_teaser',
    'djangocms_video',
    'reversion',
    'mysite',

)
</pre>

I'm working just local to test the Plugin so my DATABASES setting is:
<pre>
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'HOST': 'localhost',
        'NAME': 'project.db',
        'PASSWORD': '',
        'PORT': '',
        'USER': ''
    }
}</pre>
 
My migration command is <code>$python manage.py makemigrations</code> then <code>$python manage.py migrate</code> but i get the error allready after <code>makemigrations</code>.

And here my MIGRATION_MODULES: 
<pre>
MIGRATION_MODULES = {
    'djangocms_flash': 'djangocms_flash.migrations_django',
    'djangocms_file': 'djangocms_file.migrations_django',
    'djangocms_inherit': 'djangocms_inherit.migrations_django',
    'djangocms_column': 'djangocms_column.migrations_django',
    'djangocms_video': 'djangocms_video.migrations_django',
    'djangocms_picture': 'djangocms_picture.migrations_django',
    'djangocms_googlemap': 'djangocms_googlemap.migrations_django',
    'djangocms_style': 'djangocms_style.migrations_django',
    'djangocms_teaser': 'djangocms_teaser.migrations_django',
    'filer': 'filer.migrations_django',
}
</pre>

regards Manuel

**Comment by cyberstar** [comment]
Please delete 'filer': 'filer.migrations_django', from ``MIGRATION_MODULES`` that is the root cause of your issue.

Also if you are only applying migrations - don't run ``makemigrations``.
Also please consider putting all cms dependent packages after cms in installed_apps because with your current setup you might get other issues in future.

br.

**Comment by LepusSorbas** [comment]
Very nice working now!!! Thanks o lot!!!
