### ISSUE TITLE
Move docs to readthedocs.com

### ISSUE THREAD

**Issue by zanderle** [aldryn/aldryn-bootstrap3#73]
Much more readable to have to docs on readthedocs.com than github wiki

**Comment by FinalAngel** [comment]
the wiki has been disabled and we expanded the readme for all relevant information

**Comment by harrisonwanghao** [comment]
where can I get the docs on readthedocs.com or readthedocs.org ?  I search both of them , but nothing .  I want to find some docs about carousel . Could anyone help me ?
