### ISSUE TITLE
Create Modal plugin

### ISSUE THREAD

**Issue by FinalAngel** [aldryn/aldryn-bootstrap3#8]
http://getbootstrap.com/javascript/#modals

**Comment by zbyte64** [comment]
Was this closed as rejected? Or are pull requests welcomed for implementing this feature?

**Comment by FinalAngel** [comment]
@zbyte64 I closed this as after review, an integration as plugin is much more difficult for the user to implement than expected. I'd welcome suggestions how to solve it though.

**Comment by zbyte64** [comment]
For the sake of others needing to do this, here is what we did:

* Create a "modal" `static_placeholder` right under the `body` tag
* Register modals snippets and add them to the "modal" placeholder
* Add buttons elsewhere with the appropriate data attributes (data-target & data-toggle)


Here are some rough ideas to make this process easier:

* Rendering the modal could be done with an explicit template tag, while the plugin itself renders nil. 
* LinkMixin could add an additional field for targeting a modal with an id OR select a registered modal.

**Comment by FinalAngel** [comment]
thanks for the inputs / ideas @zbyte64
