### ISSUE TITLE
aldryn-bootstrap Accordion wasn't collapse items properly

### ISSUE THREAD

**Issue by Jone1** [aldryn/aldryn-bootstrap3#90]
I would like to use boostrap accordion and one item can be open at a time.

Expected Solution:

```
    jQuery(document).ready(function () {
    jQuery('#accordion').collapse();

    jQuery('#accordion .panel-heading a').on('click', function (e) {
        if (jQuery(this).parents('.panel').children('.panel-collapse').hasClass('in')) {
            e.stopPropagation();
        }
        e.preventDefault();
    });
});
```

It works properly in the bootstrap accordion, but in aldryn-bootstrap elements aren't collapse.

This is probably due to the fact that #accordion, .panel and .collapse are not direct descendants. 
(.cms-plugin is between #accortion and .panel)

**Comment by FinalAngel** [comment]
This has been fixed in the latest django-cms 3.4 :)
