### ISSUE TITLE
Json object must be str, not dict

### ISSUE THREAD

**Issue by songmink** [aldryn/aldryn-bootstrap3#93]
A few days ago, I installed djangocms(stable) with bootstrap3. At that time there was no error.
Yesterday, I installed new one as same as before my installing it and I got this error on jsonfield when I saved carousel image. Now, I tested v1.0.8 and there was no error on v1.0.8.

**Comment by binuks** [comment]
Are you using PostgreSQL 9.4? This package has a dependency on djangocms-attributes-field and that package had bugs with JSONField usage in PostgreSQL which were fixed recently. Check if upgrading to the latest version of djangocms-attributes-field (0.0.6 as of today) helps. The upgrade fixed similar errors I got with the aldryn-bootstrap3 link/button plugin.

**Comment by songmink** [comment]
Yes, I am using Python3.4, Postgresql9.4 on Debian Jessie server.
I'm gonna check it, thank you.

**Comment by czpython** [comment]
@songmink 
Closing, feel free to create a new ticket if this is still an issue with the latest djangocms-attributes-field
