### ISSUE TITLE
Offset-0 in columns

### ISSUE THREAD

**Issue by lmanzurv** [aldryn/aldryn-bootstrap3#96]
The column plugin doesn't allow col-*-offset-0 although bootstrap allows them. They have to be added on the additional classes field and cannot be set in the offset field for the corresponding size

**Comment by vxsx** [comment]
They should be allowed since https://github.com/aldryn/aldryn-bootstrap3/pull/86

**Comment by vxsx** [comment]
It was released in version 1.1.0, can you please confirm?

**Comment by lmanzurv** [comment]
Yes, I'm sorry, hadn't noticed the update. Already working
